### PR TITLE
Rename Untitled Folder "our-first-app"

### LINKED ISSUE #37: Directory name "untitled" appears in user-facing URLs
Directory name "untitled" appears in the book URL, e.g. https://docs.elementary.io/develop/writing-apps/untitled/the-build-system, and should be renamed to something like "our-first-app".

### PR DESCRIPTION
**Pull request by jneplokh**
Resolves #37 

- Changed the folder name
- Updated the links in SUMMARY.md

### CODE REVIEW

**Comment by jneplokh** [comment]
Hey just checking in, could someone review this?

Thank you!!

**Comment by jneplokh** [comment]
Hey,

Just bumping this to see if someone could review this PR? 

Thanks!

**Comment by jeremypw** [comment]
There seems to be several unchanged references to the `untitled` folder:
```
grep -nHIrF --include=*.md -- untitled (in directory: /media/jeremy/Shared/shared_data/Vala/Elementary/docs-branches/Forks/jneplokh/docs)
./appcenter/publishing-requirements.md:21:Your app must come with [Debian packaging](https://docs.elementary.io/develop/writing-apps/untitled/packaging). elementary OS uses Debian packages to manage software installation and updates. Your app cannot be downloaded without it. Your Debian packaging must not manually modify filesystem permissions.
./appcenter/publishing-requirements.md:37:Your app must install an [appdata.xml file](https://docs.elementary.io/develop/writing-apps/untitled#appdata-xml) to `/usr/share/metainfo`. AppCenter uses this metadata to create a listing for your app. It cannot be displayed in AppCenter without it.
./appcenter/publishing-requirements.md:49:Your app must install a [.desktop file](https://docs.elementary.io/develop/writing-apps/untitled#the-desktop-file) to `/usr/share/applications`. elementary OS uses a .desktop file to display your app in the applications launcher and the dock. Without this file, your app will not be visible to users.
./README.md:19:{% page-ref page="writing-apps/untitled/" %}
./apis/notifications.md:13:3. Create a `meson.build` file. If you don't remember how to set up Meson, go back to the [previous section](../writing-apps/untitled/the-build-system.md) and review.
./apis/notifications.md:14:4. Remember how to [make a .desktop file](../writing-apps/untitled/#the-desktop-file)? Excellent! Make one for this project, but this time, since your app will be displaying notifications, add `X-GNOME-UsesNotifications=true` to the end of the file. This is needed so that users will be able to set notification preferences for your app in the system's notification settings.
Search completed with 6 matches.
```

**Review by jeremypw — CHANGES_REQUESTED** [review]
See above comment

**Comment by jneplokh** [comment]
Oh, yeah, whoops. Just pushed the requested changes with the updated references!

**Review by jeremypw — APPROVED** [review]
Looks good now - thanks for this!

**Comment by jneplokh** [comment]
No problem!

**Pull request merged**
